gui:
  theme:
    activeBorderColor:
      - "#EC5F99"
      - bold
    inactiveBorderColor:
      - "#454545"
    optionsTextColor:
      - "#70E5E3"
    selectedLineBgColor:
      - "#333333"
    selectedRangeBgColor:
      - "#454545"
    cherryPickedCommitFgColor:
      - "#53D14C"
    unstagedChangesColor:
      - "#ff0000"
    defaultFgColor:
      - "#F7EDED"
    searchingActiveBorderColor:
      - "#FCDA04"
